-- db/schema.sql
-- RiskShield MVP schema (Phase 5, Task 1)
-- Tables: user_profile, transactions, scored_transactions
-- Do NOT include feedback_labels yet — that's a later stretch-phase table.

-- Enable pgcrypto extension for UUID support (run once per database)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- user_profile: Stores aggregated user behavioral statistics
-- Used for computing velocity and amount deviation features
-- Primary key is user_id (UUID) for direct lookups
CREATE TABLE user_profile (
    user_id             UUID PRIMARY KEY,
    avg_txn_amount      NUMERIC(12,2) DEFAULT 0,
    std_txn_amount      NUMERIC(12,2) DEFAULT 0,
    txn_count           INTEGER DEFAULT 0,
    last_device_id      TEXT,
    last_country        TEXT,
    last_latitude       NUMERIC(9,6),
    last_longitude      NUMERIC(9,6),
    updated_at          TIMESTAMPTZ DEFAULT now()
);

-- transactions: Raw incoming transaction records
-- Primary key is txn_id (UUID, auto-generated by gen_random_uuid)
-- Foreign key to user_profile ensures referential integrity
-- Index on (user_id, created_at DESC) for efficient velocity queries:
--   "get all transactions for user_id in last 24 hours" is the exact query pattern
CREATE TABLE transactions (
    txn_id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL REFERENCES user_profile(user_id),
    amount              NUMERIC(12,2) NOT NULL,
    currency            TEXT NOT NULL,
    merchant_id         TEXT,
    device_id           TEXT,
    ip_address          INET,
    country             TEXT,
    latitude            NUMERIC(9,6),
    longitude           NUMERIC(9,6),
    created_at          TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_txn_user_time ON transactions (user_id, created_at DESC);

-- scored_transactions: Immutable log of all scoring decisions
-- Primary key is auto-incrementing bigint (log entry number)
-- Foreign key to transactions.txn_id links back to the raw transaction
-- feature_snapshot stores the exact 10-element feature dict used for this score (as JSONB)
--   This enables auditability: we can later ask "what features led to this decision?"
-- shap_values (reserved for future use) will store SHAP-based model interpretability
-- Index on (flagged, scored_at DESC) supports the query:
--   "get recently flagged transactions" (useful for dashboard, alerts, etc.)
CREATE TABLE scored_transactions (
    id                  BIGSERIAL PRIMARY KEY,
    txn_id              UUID NOT NULL REFERENCES transactions(txn_id),
    risk_score          NUMERIC(5,4) NOT NULL,
    flagged             BOOLEAN NOT NULL,
    model_version       TEXT NOT NULL,
    feature_snapshot    JSONB NOT NULL,
    shap_values         JSONB,
    scored_at           TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_scored_flagged ON scored_transactions (flagged, scored_at DESC);
